name: CI

on: [pull_request, push]

permissions: {}

jobs:
  nodejs:
    name: Check CSS
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: install tools
        run: npm install
      - name: lint code
        run: npm run lint
      - name: format code
        run: |
          npm run format
          git diff --exit-code
